### ISSUE TITLE
Check static force terms when the load step size changes

### ISSUE THREAD

**Issue by kmokstad** [OPM/IFEM-PoroElasticity#29]
If you run the nonlinear quasi-static fracturedynamics application (option -qstatic), The solution diverges when changing the load increment size, even by a small amount and no change in the external load. This cannot be right. Are the poro-elastic load terms correct in this case?

Reproduce by running `FractureDynamics Miehe71.xinp -nocrack -poro -qstatic -stopTime 11.01`
whereas `FractureDynamics Miehe71.xinp -nocrack -poro -qstatic -stopTime 11` works.

In the latter case the last increment has the same size as the previous one, whereas in the former it is only 1% longer.

**Comment by akva2** [comment]
if you add

```
<poroelasticity>
  <scaling value="1.0"/>
</poroelasticity>
```
it works (better).

**Comment by TheBB** [comment]
There's a scaling factor built in here to keep numbers roughly the same size. If not provided in the input file (which is the case in Miehe71.xinp from what I can tell) it's computed dynamically:

https://github.com/OPM/IFEM-PoroElasticity/blob/99c4d484d38a7db654c0771cff718e3e14f490dd/PoroElastic/PoroElasticity.C#L95-L97

This function is intended to be independent of `X`, and of course if `dt` varies then mayhem will ensue. It's probably best to set the scale factor in the input file. We can also try to ensure that `getScale` saves the computed value, not sure how good that is for multithreaded assembly but at least it can't be worse than silently failing like this.

**Comment by kmokstad** [comment]
Was not aware of this fact. If the scaling factor needs to be constant (in space and time) it does not make sense to compute it like this in evalInt. Then I suggest to do this calculation during problem setup instead, using the size of the first load/time step and some X-value in the center of the domain (or at a point with the most characteristic material properties, in most cases the stiffness properties are constant anyway), and the store this value as a class member. But of coarse, specifying as input is the easiest.
